### PR TITLE
add config toggle to disable any package updates on cloud-init

### PR DESCRIPTION
**Pull request by maigl**
This adds a config toggle to disable any package install or updates during boot / cloud-init.

This PR belongs to https://github.com/cloudbase/garm/pull/84

Remarks:

I'm no really happy to duplicate this entire function just to add this `if`. 

<sub>Michael Kuhnt <michael.kuhnt@mercedes-benz.com> Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))
</sub>

### CODE REVIEW

**Comment by gabriel-samfira** [comment]
Yeah, you are right. In the future, I think we should make this part a bit more granular to allow easy customization. For now, I think the easiest and quickest thing to do is add an extra param to ```GetCloudConfig()``` function in garm itself that disables updates. This way we don't have to copy it just for this.

Feel free to create a PR in garm that adds the flag. We can vendor it here and make use of it.

**Comment by maigl** [comment]
> For now, I think the easiest and quickest thing to do is add an extra param to `GetCloudConfig()` function
.. or maybe we could add a new field UserDataOptions to the `BootstrapInstance` struct? This could be the first step towards more customization..

**Comment by gabriel-samfira** [comment]
If you remove the replace and update to the latest commit of garm, we can merge this one too

**Comment by maigl** [comment]
> If you remove the replace and update to the latest commit of garm, we can merge this one too

done

**Comment by gabriel-samfira** [comment]
Thanks!

**Pull request merged**
